Membuka Imprint Forensics...
At D:\VS Code\projects\HackathonIqbal\inprint.ps1:51 char:53
+ ... Host "========================================" -ForegroundColor Cyan
+                                                   ~~~~~~~~~~~~~~~~~~~~~~~
The string is missing the terminator: ".
At D:\VS Code\projects\HackathonIqbal\inprint.ps1:21 char:35
+ if (-not (Test-Path $venvPython)) {
+                                   ~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString


Jika tulisan ini terlihat, berarti server telah berhenti atau ada error.